spring:
  datasource:
    url: jdbc:h2:mem:proofhire
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8081

jwt:
  secret: 9A8B7C6D5E4F3G2H1I0J9K8L7M6N5O4P3Q2R1S0T9U8V7W6X5Y4Z3A2B1C0D9E8F
  expiration: 86400000 # 24 hours

cors:
  allowed-origins: "http://localhost:5173"
